# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from amaas.grpc.protos import scan_pb2 as amaas_dot_grpc_dot_protos_dot_scan__pb2


class ScanStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.stream_stream(
                '/amaas.scan.v1.Scan/Run',
                request_serializer=amaas_dot_grpc_dot_protos_dot_scan__pb2.C2S.SerializeToString,
                response_deserializer=amaas_dot_grpc_dot_protos_dot_scan__pb2.S2C.FromString,
                )


class ScanServicer(object):
    """Interface exported by the server.
    """

    def Run(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScanServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.stream_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=amaas_dot_grpc_dot_protos_dot_scan__pb2.C2S.FromString,
                    response_serializer=amaas_dot_grpc_dot_protos_dot_scan__pb2.S2C.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'amaas.scan.v1.Scan', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scan(object):
    """Interface exported by the server.
    """

    @staticmethod
    def Run(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/amaas.scan.v1.Scan/Run',
            amaas_dot_grpc_dot_protos_dot_scan__pb2.C2S.SerializeToString,
            amaas_dot_grpc_dot_protos_dot_scan__pb2.S2C.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
